# Generated by Django 3.1.7 on 2021-04-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springrevolution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
