# Generated by Django 3.1.7 on 2021-04-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springrevolution', '0002_user_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=32)),
            ],
        ),
    ]
