# Generated by Django 3.1.7 on 2021-04-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('springrevolution', '0003_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
