# Generated by Django 3.1.7 on 2021-04-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springrevolution', '0004_auto_20210412_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
