# Generated by Django 3.1.7 on 2021-04-16 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springrevolution', '0008_user_time_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receiving_date',
            field=models.DateField(default=datetime.date(2021, 4, 16)),
        ),
    ]
