# Generated by Django 3.1.7 on 2021-04-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('springrevolution', '0011_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
    ]
